name: Generar Ejecutable Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar PyInstaller y librerias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Si tu app.py usa librerias externas (como pandas, flask, etc.), agrégalas abajo:
        # pip install pandas openpyxl flask

    - name: Compilar app a .exe con PyInstaller
      run: |
        pyinstaller --noconsole --onefile --add-data "devonne.html;." --add-data "miranda.html;." --add-data "suresh.html;." --add-data "suresh_2.html;." --add-data "william.html;." app.py

    - name: Subir el archivo EXE generado
      uses: actions/upload-artifact@v4
      with:
        name: MiAplicacionWindows
        path: dist/app.exe
